import { randChoice, randInt, sampleDistinctInts, shuffle } from "@/lib/rng";
import { buildChoicesFromStrings } from "./mathUtils";
import type { Skill } from "@/lib/types";

const PLACE_NAMES = ["ones", "tens", "hundreds", "thousands", "ten thousands", "hundred thousands", "millions", "ten millions", "hundred millions"];

function digitAtPlace(n: number, placeIndex: number): number {
  return Math.floor(n / 10 ** placeIndex) % 10;
}

function numberToWords(n: number): string {
  const ones = ["", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"];
  const teens = ["ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"];
  const tens = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"];
  function threeDigits(x: number): string {
    let s = "";
    if (x >= 100) {
      s += `${ones[Math.floor(x / 100)]} hundred`;
      x %= 100;
      if (x > 0) s += " and ";
    }
    if (x >= 20) {
      s += tens[Math.floor(x / 10)];
      if (x % 10 > 0) s += `-${ones[x % 10]}`;
    } else if (x >= 10) {
      s += teens[x - 10];
    } else if (x > 0) {
      s += ones[x];
    }
    return s;
  }
  if (n === 0) return "zero";
  const millions = Math.floor(n / 1_000_000);
  const thousands = Math.floor((n % 1_000_000) / 1000);
  const rest = n % 1000;
  const parts: string[] = [];
  if (millions > 0) parts.push(`${threeDigits(millions)} million`);
  if (thousands > 0) parts.push(`${threeDigits(thousands)} thousand`);
  if (rest > 0) parts.push(threeDigits(rest));
  return parts.join(" ");
}

const REAL_LIFE_COUNTS = [
  { subject: "the number of people who attended a national census in a county", unit: "" },
  { subject: "the population of a Kenyan town", unit: "" },
  { subject: "the total maize harvest recorded across a county, in kilograms", unit: "" },
  { subject: "the amount collected in a school's building fund, in KES", unit: "" },
  { subject: "the number of litres of milk processed by a dairy cooperative in a year", unit: "" },
  { subject: "the number of passengers who used a bus terminus in a month", unit: "" },
  { subject: "the total value of goods exported through a Kenyan port in a year, in KES", unit: "" },
  { subject: "the number of trees planted in a national reforestation drive", unit: "" },
  { subject: "the number of registered voters in a constituency", unit: "" },
  { subject: "the total electricity generated by a power station in a year, in kilowatt-hours", unit: "" },
] as const;

export const wholeNumbers: Skill = {
  id: "g7-math-n-whole-numbers",
  code: "N.1",
  subjectId: "math",
  strandId: "g7-math-numbers",
  grade: 7,
  title: "Whole numbers",
  description: "Place value and total value up to hundreds of millions, reading and writing numbers, rounding off, classifying even/odd/prime numbers, order of operations, and number sequences.",
  generate(rng) {
    const branch = randChoice(rng, ["place-value", "read-write", "round-off", "classify", "sequence", "order", "operations"] as const);

    if (branch === "place-value") {
      const n = randInt(rng, 100_000, 987_654_321);
      const placeIndex = randInt(rng, 0, 8);
      const askTotal = rng() < 0.5;
      const digit = digitAtPlace(n, placeIndex);
      const totalValue = digit * 10 ** placeIndex;
      return {
        kind: "fill-blank",
        prompt: `In the number ${n.toLocaleString()}, what is the ${askTotal ? "total value" : "place value (name)"} of the digit in the ${PLACE_NAMES[placeIndex]} position?`,
        before: askTotal ? "Total value =" : "Place value name:",
        after: "",
        correctAnswer: askTotal ? String(totalValue) : PLACE_NAMES[placeIndex],
        inputMode: "text",
        hint: askTotal ? "Total value = digit × the place's value (e.g. 3 in the hundreds place = 3 × 100 = 300)." : "The place value is the name of the column the digit sits in.",
        explanation: `The digit in the ${PLACE_NAMES[placeIndex]} position of ${n.toLocaleString()} is ${digit}. Its place value name is "${PLACE_NAMES[placeIndex]}" and its total value is $${digit} \\times 10^{${placeIndex}} = ${totalValue.toLocaleString()}$.`,
      };
    }

    if (branch === "read-write") {
      const count = 3;
      const chosen: number[] = [];
      while (chosen.length < count) {
        const n = randInt(rng, 100_000, 750_000_000);
        if (!chosen.includes(n)) chosen.push(n);
      }
      const tokens = chosen.map((n, i) => ({ id: `sym${i}`, label: n.toLocaleString() }));
      const targets = shuffle(rng, chosen.map((n, i) => ({ id: `wrd${i}`, label: numberToWords(n) })));
      const correctMap: Record<string, string> = {};
      chosen.forEach((_, i) => (correctMap[`wrd${i}`] = `sym${i}`));
      return {
        kind: "click-match",
        prompt: "Match each number (in symbols) to how it is written in words.",
        tokens,
        targets,
        correctMap,
        hint: "Break the number into millions, thousands, and the last three digits.",
        explanation: chosen.map((n) => `${n.toLocaleString()} = ${numberToWords(n)}`).join("; ") + ".",
      };
    }

    if (branch === "round-off") {
      const ctx = randChoice(rng, REAL_LIFE_COUNTS);
      const n = randInt(rng, 1_200_000, 456_789_123);
      const placeIndex = randChoice(rng, [5, 6, 7] as const); // hundred-thousands, millions, ten-millions
      const factor = 10 ** placeIndex;
      const rounded = Math.round(n / factor) * factor;
      return {
        kind: "fill-blank",
        prompt: `This chart shows ${ctx.subject}: ${n.toLocaleString()}. Round this off to the nearest ${PLACE_NAMES[placeIndex]}.`,
        before: "Rounded value =",
        after: "",
        correctAnswer: String(rounded),
        inputMode: "numeric",
        hint: `Look at the digit just to the right of the ${PLACE_NAMES[placeIndex]} place to decide whether to round up or down.`,
        explanation: `${n.toLocaleString()} rounded to the nearest ${PLACE_NAMES[placeIndex]} is ${rounded.toLocaleString()}.`,
      };
    }

    if (branch === "classify") {
      const pool = sampleDistinctInts(rng, 20, 200, 6);
      const isPrime = (x: number) => {
        if (x < 2) return false;
        for (let d = 2; d * d <= x; d++) if (x % d === 0) return false;
        return true;
      };
      const classOf = (x: number) => (isPrime(x) ? "prime" : x % 2 === 0 ? "even" : "odd");
      const items = pool.map((n) => ({ id: String(n), label: String(n) }));
      const buckets = [
        { id: "even", label: "Even (and not prime)" },
        { id: "odd", label: "Odd (and not prime)" },
        { id: "prime", label: "Prime" },
      ];
      const correctBucket: Record<string, string> = {};
      for (const n of pool) correctBucket[String(n)] = classOf(n);
      return {
        kind: "categorize",
        prompt: "Sort each number as even, odd, or prime. (2 is the only even prime — sort a prime number into the Prime bucket even if it happens to be even.)",
        items,
        buckets,
        correctBucket,
        hint: "A prime number has exactly two factors: 1 and itself. Otherwise, check the last digit for even/odd.",
        explanation: pool.map((n) => `${n} is ${classOf(n)}`).join("; ") + ".",
      };
    }

    if (branch === "sequence") {
      const kind2 = randChoice(rng, ["arithmetic", "geometric"] as const);
      if (kind2 === "arithmetic") {
        const start = randInt(rng, 2, 30);
        const step = randInt(rng, 3, 15);
        const seq = Array.from({ length: 5 }, (_, i) => start + i * step);
        const missingIdx = randInt(rng, 2, 4);
        const display = seq.map((v, i) => (i === missingIdx ? "?" : v)).join(", ");
        return {
          kind: "fill-blank",
          prompt: `Find the missing number in this sequence: ${display}`,
          before: "Missing number =",
          after: "",
          correctAnswer: String(seq[missingIdx]),
          inputMode: "numeric",
          hint: `Find the common difference between consecutive terms (here, +${step}).`,
          explanation: `Each term increases by ${step}: ${seq.join(", ")}. The missing term is ${seq[missingIdx]}.`,
        };
      }
      const start = randInt(rng, 1, 5);
      const ratio = randChoice(rng, [2, 3] as const);
      const seq = Array.from({ length: 5 }, (_, i) => start * ratio ** i);
      const missingIdx = randInt(rng, 2, 4);
      const display = seq.map((v, i) => (i === missingIdx ? "?" : v)).join(", ");
      return {
        kind: "fill-blank",
        prompt: `Find the missing number in this sequence: ${display}`,
        before: "Missing number =",
        after: "",
        correctAnswer: String(seq[missingIdx]),
        inputMode: "numeric",
        hint: `Find what each term is multiplied by to get the next term (here, ×${ratio}).`,
        explanation: `Each term is multiplied by ${ratio}: ${seq.join(", ")}. The missing term is ${seq[missingIdx]}.`,
      };
    }

    if (branch === "order") {
      const seen = new Set<number>();
      while (seen.size < 4) seen.add(randInt(rng, 1_000_000, 950_000_000));
      const values = [...seen];
      const items = values.map((v) => ({ id: String(v), label: v.toLocaleString() }));
      const sorted = [...values].sort((a, b) => a - b);
      return {
        kind: "ordering",
        prompt: "Arrange these numbers from smallest to largest.",
        instruction: "Click them in order, smallest first.",
        items: shuffle(rng, items),
        correctOrder: sorted.map(String),
        hint: "Compare the number of digits first, then compare digit by digit from the left.",
        explanation: `In order: ${sorted.map((v) => v.toLocaleString()).join(", ")}.`,
      };
    }

    // operations: 2-3 combined operations in the correct order (classical, context-free)
    const a = randInt(rng, 20, 90);
    const b = randInt(rng, 10, 60);
    const c = randInt(rng, 5, 40);
    const d = randInt(rng, 2, 12);
    const useDivision = rng() < 0.5;
    const exprParts = useDivision
      ? { expr: `${a} + ${b} \\times ${d} - ${c}`, answer: a + b * d - c, plain: `${a} + ${b} * ${d} - ${c}` }
      : { expr: `(${a} - ${c}) \\times ${d} + ${b}`, answer: (a - c) * d + b, plain: `(${a} - ${c}) * ${d} + ${b}` };
    const wrong = [String(exprParts.answer + d), String(exprParts.answer - d), String((a + b) * d - c), String(a + b - c * d)];
    const { choices, correctIndex } = buildChoicesFromStrings(rng, String(exprParts.answer), wrong);
    return {
      kind: "multiple-choice",
      prompt: `Work out: $${exprParts.expr}$`,
      choices,
      correctIndex,
      layout: "row",
      hint: "Follow the order of operations: brackets first, then multiplication/division, then addition/subtraction.",
      explanation: `$${exprParts.expr} = ${exprParts.answer}$, following the correct order of operations.`,
    };
  },
};
