import Link from "next/link";
import { TopNav } from "@/components/layout/TopNav";
import { AVAILABLE_GRADES } from "@/lib/curriculum";

const GRADE_BLURB: Record<number, string> = {
  5: "Upper Primary — numbers, measurement, geometry, and data handling.",
  6: "The final year of Upper Primary — numbers, measurement, geometry, and data handling.",
  7: "The first year of Junior School — numbers, algebra, geometry, and more.",
  8: "Numbers, algebra, geometry, and more — the middle year of Junior School.",
  9: "The senior-most Junior School grade — deeper algebra, geometry, and every subject's full breadth.",
  10: "The first year of Senior School — core subjects plus a growing set of electives.",
};

export default function Home() {
  return (
    <div className="flex min-h-screen flex-col bg-slate-50">
      <TopNav />

      <section className="bg-gradient-to-br from-green-500 via-lime-500 to-emerald-500 px-4 py-10 text-center sm:px-6">
        <h1 className="text-3xl font-extrabold text-white sm:text-4xl">CBC Quizmaster</h1>
        <p className="mx-auto mt-2 max-w-xl text-sm font-medium text-lime-50 sm:text-base">
          Endless, fresh questions for every CBC subject — generated on the fly, just like the real exam.
        </p>
      </section>

      <main className="mx-auto w-full max-w-3xl flex-1 px-4 py-10 sm:px-6">
        <h2 className="text-center text-lg font-extrabold text-slate-700">Choose your grade</h2>
        <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
          {AVAILABLE_GRADES.map((grade) => (
            <Link
              key={grade}
              href={`/grade/${grade}`}
              className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"
            >
              <div className="bg-gradient-to-r from-sky-400 to-sky-600 px-5 py-6 text-center">
                <span className="text-4xl font-extrabold text-white">Grade {grade}</span>
              </div>
              <div className="p-4 text-center">
                <p className="text-sm text-slate-500">{GRADE_BLURB[grade]}</p>
                <span className="mt-3 inline-block rounded-full bg-sky-50 px-3 py-1 text-xs font-bold text-sky-700 group-hover:bg-sky-100">
                  Start practicing →
                </span>
              </div>
            </Link>
          ))}
        </div>

        <p className="mt-10 text-center text-xs text-slate-400">
          Every question is generated by a parameterized template — no two students see the exact same numbers.
        </p>

        <div className="mt-10 text-center">
          <Link
            href="/tools/scheme-of-work"
            className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-bold text-slate-600 shadow-sm transition-colors hover:border-green-300 hover:text-green-700"
          >
            🧑‍🏫 Teacher tools: Scheme of Work Generator
          </Link>
        </div>
      </main>
    </div>
  );
}
