"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { TopNav } from "@/components/layout/TopNav";
import { SubjectIcon } from "@/components/icons/SubjectIcon";
import { subjectsWithStrands } from "@/lib/curriculum";
import { skillsForSubject } from "@/skills";

const COLOR_MAP: Record<string, { gradient: string; soft: string; text: string }> = {
  sky: { gradient: "from-sky-400 to-sky-600", soft: "bg-sky-50", text: "text-sky-700" },
  violet: { gradient: "from-violet-400 to-violet-600", soft: "bg-violet-50", text: "text-violet-700" },
  emerald: { gradient: "from-emerald-400 to-emerald-600", soft: "bg-emerald-50", text: "text-emerald-700" },
  amber: { gradient: "from-amber-400 to-amber-600", soft: "bg-amber-50", text: "text-amber-700" },
  rose: { gradient: "from-rose-400 to-rose-600", soft: "bg-rose-50", text: "text-rose-700" },
  indigo: { gradient: "from-indigo-400 to-indigo-600", soft: "bg-indigo-50", text: "text-indigo-700" },
  lime: { gradient: "from-lime-400 to-lime-600", soft: "bg-lime-50", text: "text-lime-700" },
  fuchsia: { gradient: "from-fuchsia-400 to-fuchsia-600", soft: "bg-fuchsia-50", text: "text-fuchsia-700" },
  orange: { gradient: "from-orange-400 to-orange-600", soft: "bg-orange-50", text: "text-orange-700" },
  purple: { gradient: "from-purple-400 to-purple-600", soft: "bg-purple-50", text: "text-purple-700" },
  teal: { gradient: "from-teal-400 to-teal-600", soft: "bg-teal-50", text: "text-teal-700" },
  blue: { gradient: "from-blue-400 to-blue-600", soft: "bg-blue-50", text: "text-blue-700" },
  cyan: { gradient: "from-cyan-400 to-cyan-600", soft: "bg-cyan-50", text: "text-cyan-700" },
  red: { gradient: "from-red-400 to-red-600", soft: "bg-red-50", text: "text-red-700" },
  yellow: { gradient: "from-yellow-400 to-yellow-600", soft: "bg-yellow-50", text: "text-yellow-700" },
  green: { gradient: "from-green-400 to-green-600", soft: "bg-green-50", text: "text-green-700" },
  pink: { gradient: "from-pink-400 to-pink-600", soft: "bg-pink-50", text: "text-pink-700" },
};

export default function GradeDashboard() {
  const params = useParams<{ grade: string }>();
  const grade = Number(params.grade);
  const groups = subjectsWithStrands(grade);

  return (
    <div className="flex min-h-screen flex-col bg-slate-50">
      <TopNav grade={grade} />

      <section className="bg-gradient-to-br from-green-500 via-lime-500 to-emerald-500 px-4 py-10 text-center sm:px-6">
        <h1 className="text-3xl font-extrabold text-white sm:text-4xl">Grade {grade} CBC Practice</h1>
        <p className="mx-auto mt-2 max-w-xl text-sm font-medium text-lime-50 sm:text-base">
          Endless, fresh questions for every Grade {grade} subject — generated on the fly, just like the real exam.
        </p>
      </section>

      <main className="mx-auto w-full max-w-6xl flex-1 px-4 py-8 sm:px-6">
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {groups.map(({ subject, strands }) => {
            const skillCount = skillsForSubject(subject.id, grade).length;
            const palette = COLOR_MAP[subject.color] ?? COLOR_MAP.sky;

            return (
              <Link
                key={subject.id}
                href={`/grade/${grade}/subject/${subject.id}`}
                className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"
              >
                <div className={`flex items-center gap-3 bg-gradient-to-r ${palette.gradient} px-4 py-3`}>
                  <span className="grid h-9 w-9 place-items-center rounded-lg bg-white/25 text-white">
                    <SubjectIcon icon={subject.icon} className="h-5 w-5" />
                  </span>
                  <span className="text-base font-extrabold text-white">{subject.name}</span>
                </div>
                <div className="space-y-1.5 p-4">
                  <p className="text-xs text-slate-400">{strands.length} strands · Grade {grade}</p>
                  <p className={`inline-block rounded-full px-2.5 py-1 text-xs font-bold ${palette.soft} ${palette.text}`}>
                    {skillCount > 0 ? `${skillCount} practice skills ready` : "Skills coming soon"}
                  </p>
                </div>
              </Link>
            );
          })}
        </div>

        <p className="mt-10 text-center text-xs text-slate-400">
          Every question is generated by a parameterized template — no two students see the exact same numbers.
        </p>
      </main>
    </div>
  );
}
